### ISSUE TITLE
Unable to set directory

### ISSUE THREAD

**Issue by SomethinClever** [kuba2k2/spicetify-beat-saber#8]
I am unable to type or paste my BeatSaber file directory into the settings box. Opening the "Browse for directory" menu leads to endless loading. 

https://github.com/kuba2k2/spicetify-beat-saber/assets/138703198/134ed9e3-eb85-41f1-852e-1906ea899113

**Comment by kuba2k2** [comment]
2.0.1 is the correct version for backend. Typing or pasting the path is not supported, you need to use the browser button.

Please enable devtools in spicetify (spicetify enable-devtools IIRC), press Ctrl+Shift+I, navigate to the Console tab and open the directory picker again. Post screenshots of errors, if any occur.

**Comment by AstraxCZ** [comment]
Seems path null left error

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/2f486757-62ee-4b45-abff-cca9f92e3afd)
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/391f3bac-caf7-4826-b33a-4c4322de0f25)


But path like e: or c: lists folders and files it the location


![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/dced89ad-3dd7-47f4-9c40-a2987ba6de81)
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/184b707f-9506-430d-ae12-2d9f95e4a3dd)

**Comment by kuba2k2** [comment]
Thanks, this should be fixed in extension v2.1.1 and backend v2.0.2.

**Comment by AstraxCZ** [comment]
good to know

**Comment by AstraxCZ** [comment]
Works good now:
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/743dd1a8-7754-4543-a5d4-f3a8652d7f1a)


![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/a02d3eac-2ea2-4787-953d-ee6a83fefd46)



Thanks for your time

**Comment by Automaetic-official** [comment]
I installed extension v2.1.1 and backend v2.0.2, but the problem persists for me.


Just after starting spotify:

![01_just_after_starting_spotify](https://github.com/kuba2k2/spicetify-beat-saber/assets/137318595/2e3ee545-65f1-44d8-96ba-6a0a4f1a3bfa)


More errors appeared shortly after:

![02_more_errors_appeared_shortly_after](https://github.com/kuba2k2/spicetify-beat-saber/assets/137318595/24487d60-becf-4eda-bd97-f55fe20d1a81)


When trying to set beat saber directory:

![03_when_trying_to_set_beat_saber_directory](https://github.com/kuba2k2/spicetify-beat-saber/assets/137318595/d8924f7d-a4cb-45f9-a8af-e4af06879eec)

**Comment by AstraxCZ** [comment]
do you have backend connected?

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/88210947/98606ff2-4c17-4496-8c63-d9f8b0a0c1f3)

**Comment by kuba2k2** [comment]
These errors are caused by the Marketplace extension, not by the Beat Saber extension. In fact, the only error from this extension is:
![obraz](https://github.com/kuba2k2/spicetify-beat-saber/assets/30433568/aedf73b5-e6c8-48c5-a77c-4756b00c23dd)
which can indicate either outdated backend, or backend not running at all. Did you reboot your PC after installation?

**Comment by Automaetic-official** [comment]
Thank you for being fast and helpful :)
Rebooting worked its magic yet again
